### ISSUE TITLE
Banner images scale oddly 

### ISSUE THREAD

**Issue by joncamfield** [usable-tools/usable-tools#1]
At "middle" widths, the banner images scale oddly, adding background-colored whitespace on top and bottom.  See attached screenshot taking at a width of 994.
![Screenshot from 2019-06-14 10-38-28](https://user-images.githubusercontent.com/212852/59500164-cb5fd180-8e90-11e9-8002-8653390b0900.png)

**Comment by squiggy** [comment]
Fixed in commit 9f04a5cabe0db86b2b868e4ae4f46514a658a6dd

**Comment by joncamfield** [comment]
confirmed
