### ISSUE TITLE
Carousel image+text scaling issues

### ISSUE THREAD

**Issue by joncamfield** [usable-tools/usable-tools#2]
At middle widths (e.g. 1024x768) the carousel images overlap text.  At mobile widths, the images disappear altogether.

1024 width
![Screenshot from 2019-06-14 10-43-08](https://user-images.githubusercontent.com/212852/59500392-38736700-8e91-11e9-92c6-6146233b675a.png)

mobile layout
![Screenshot from 2019-06-14 10-42-50](https://user-images.githubusercontent.com/212852/59500397-3b6e5780-8e91-11e9-8258-6e7a9fc812cf.png)

**Comment by squiggy** [comment]
Fixed in commit 9bcab2cea21c06b61b63eca5c5afcec854ca7a93

**Comment by joncamfield** [comment]
confirmed
