### ISSUE TITLE
Odd header layout in mobile width

### ISSUE THREAD

**Issue by joncamfield** [usable-tools/usable-tools#3]
The orange arrow element breaks and creates a lot of useless space and a confusing interface (same color and sometimes overlaps the actual functional down arrow)

![Screenshot from 2019-06-14 10-44-05](https://user-images.githubusercontent.com/212852/59500512-838d7a00-8e91-11e9-944d-2231f53cb73c.png)

**Comment by squiggy** [comment]
This was fixed in commit aac5e6aedf33f75f205ebc9fd7a15b859ef758a2

**Comment by joncamfield** [comment]
Confirmed on local
