### ISSUE TITLE
Persona Filtering

### ISSUE THREAD

**Issue by joncamfield** [usable-tools/usable-tools#4]
Persona listing page currently has no filtering option. Design concept exists for this to leverage metadata (or other options, not hard requirement) to filter personas based on attributed. 

Ticket from tracker: "Use listjs; use digital assets and design already established, but use one “block” for the search bar; add helper text around syntax we use for personas" 

Update: "There wasn't a javascript plugin that matched this functionality. I thought listjs did this but it only filters by a search field, and doesn't support multiple select dropdowns. I'm so sorry I was incorrect about my projection for completing this feature. Completing this will require more research and maybe also working with someone who has stronger javascript skills than I do. Is this something we can push off to complete after launch or in a phase 2 of work on the site?  "

Could we change to a free-form, live-updating text filter, and suggest specific terms to search against, suggest auto-fill/auto-complete from the tags, or do some other tricks using the listjs functionality?

**Comment by joncamfield** [comment]
While not ideal, Algolia's Community/Free tier may be the fastest, smoothest way to implement this? https://harrycresswell.com/articles/hugo-algolia/ , https://harrycresswell.com/articles/hugo-algolia-2/

**Comment by squiggy** [comment]
Hi Jon. I have ListJS setup on the personas page now. I just finished this right before I saw your comment.

**Comment by joncamfield** [comment]
Awesome! I'd definitely prefer a solution that didn't rely on a commercial service, but wanted to be pragmatic.

**Comment by joncamfield** [comment]
Still testing on the listjs implementation; a few problems:

* Can only search 1 term, adding a space seems to nuke the term.  I tried adding the fuzzysearch configuration in but it has not helped
* (future) I think it is possible to do the drop-downs, but it looks like it might need some jquery hacking: https://codepen.io/waynehoover/pen/KBqhF

**Comment by joncamfield** [comment]
@squiggy Any help around the problems of being able to search more than one term would be helpful here. It also occurs on their example at https://listjs.com/ ; so it may be just a restriction of ListJS overall

**Comment by joncamfield** [comment]
The remainder of the work here is tracked in #14
