### ISSUE TITLE
Automate deployment via Travis

### ISSUE THREAD

**Issue by joncamfield** [usable-tools/usable-tools#5]
Implement CI to deploy hugo built site from source to master to serve via gh-pages automatically upon changes to source repo.

**Comment by joncamfield** [comment]
Note: If script takes longer or there are barriers; manually update gh-pages for soft launch

**Comment by squiggy** [comment]
I updated .travis.yml and tested it in a personal account. To get automatic deploys working here, you will need to create a personal access token: https://github.com/settings/tokens. You will then need to add this token to environment variables for the repository here: https://travis-ci.com/usable-tools/usable-tools/settings

**Comment by joncamfield** [comment]
This seems to have been a very weird permissions error between travis and gh that is at least for now resolved.
